### ISSUE TITLE
KeyError: 'NotAfter'

### ISSUE THREAD

**Issue by tifend** [bijohnvincent/NotifyAcmCertificateExpiry#1]
We are getting this error while running the provided function (some private/public domain has expired cert in ACM - Imported cert)

```
NotAfter': KeyError Traceback (most recent call last): File "/var/task/lambda_function.py", line 31, in lambda_handler certificateExpiresIn = certificateDetails['NotAfter'].replace(tzinfo=None) - now KeyError: 'NotAfter'
'NotAfter': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 31, in lambda_handler
    certificateExpiresIn = certificateDetails['NotAfter'].replace(tzinfo=None) - now
KeyError: 'NotAfter
```
If we run the same lambda function without having any domain or cert in ACM(Empty ACM), it works fine. Please see the attached screenshots.

![lambdasuccess](https://user-images.githubusercontent.com/40413277/81720352-eae5ec80-949b-11ea-931d-2c473c403060.PNG)

**Comment by tifend** [comment]
bijohnvincent, Can you please help me on this matter?

**Comment by bijohnvincent** [comment]
Hello,
Variable 'certificateDetails' must have a key 'NotAfter'. Please add a print statement above the line you are getting error and check what you are getting there.

>         print (certificateDetails)
>         certificateExpiresIn = certificateDetails['NotAfter'].replace(tzinfo=None) - now

You must get a python dictionary in the following format:

> {'CertificateArn': 'arn:aws:acm:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
>  'DomainName': '*.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com',
>  'SubjectAlternativeNames': ['*.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com'],
>  'DomainValidationOptions': [
>      {'DomainName': '*.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com',
>      'ValidationDomain': '*.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
>      'ValidationStatus': 'SUCCESS',
>      'ResourceRecord': {'Name': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com.',
>          'Type': 'CNAME',
>          'Value': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.acm-validations.aws.'},
>      'ValidationMethod': 'DNS'}
>  ],
>  'Serial': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
>  'Subject': 'CN=*.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.com',
>  'Issuer': 'Amazon',
>  'CreatedAt': datetime.datetime(2020, 4, 11, 7, 32, 20, tzinfo=tzlocal()),
>  'IssuedAt': datetime.datetime(2020, 4, 11, 7, 34, 33, tzinfo=tzlocal()),
>  'Status': 'ISSUED',
>  'NotBefore': datetime.datetime(2020, 4, 11, 0, 0, tzinfo=tzlocal()),
>  'NotAfter': datetime.datetime(2022, 6, 11, 12, 0, tzinfo=tzlocal()),
>  'KeyAlgorithm': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
>  'SignatureAlgorithm': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
>  'InUseBy': ['arn:aws:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'],
>  'Type': 'AMAZON_ISSUED',
>  'KeyUsages': [
>      {'Name': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'},
>      {'Name': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
>  ],
>  'ExtendedKeyUsages': [
>      {'Name': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'OID': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'},
>      {'Name': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'OID': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
>  ],
>  'RenewalEligibility': 'ELIGIBLE',
>  'Options': {'CertificateTransparencyLoggingPreference': 'ENABLED'}}

**Comment by tifend** [comment]
Thanks Bijohnvincent! There is no issue with your code. There was a problem with AWS ACM end.
